{"name": "test_login[reqdata1-respdata1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert '登录成功' == '用户名或密码有误'\n  - 用户名或密码有误\n  + 登录成功", "trace": "self = <testcase.testLogin.TestLogin object at 0x110158fd0>\nreqdata = {'password': '88888888', 'username': ''}\nrespdata = {'error_code': 'FAIL', 'reason': '用户名或密码有误', 'request_id': '0e1beb6a-d1f3-4beb-8b9a-08e499a3e465'}\n\n    @mark.parametrize('reqdata,respdata',login_xls)\n    def test_login(self,reqdata,respdata):\n        response=RunMain().run_main('post',url,reqdata)\n        print('实际结果为：',response)\n        print('*'*30)\n        print('预期结果为：',respdata)\n>       assert response['reason']==respdata['reason']\nE       AssertionError: assert '登录成功' == '用户名或密码有误'\nE         - 用户名或密码有误\nE         + 登录成功\n\ntestLogin.py:24: AssertionError"}, "parameters": [{"name": "reqdata", "value": "{'username': '', 'password': '88888888'}"}, {"name": "respdata", "value": "{'error_code': 'FAIL', 'reason': '用户名或密码有误', 'request_id': '0e1beb6a-d1f3-4beb-8b9a-08e499a3e465'}"}], "start": 1615192468362, "stop": 1615192468374, "uuid": "beabe54d-1056-4484-9e4a-98748078e6e0", "historyId": "114ca8b6db0c13876876e4828d299dbf", "testCaseId": "9a22eb6dd1f861c809eb24e8910b9d6a", "fullName": "testcase.testLogin.TestLogin#test_login", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "testLogin"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "12345.local"}, {"name": "thread", "value": "6779-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.testLogin"}]}